backend:
  name: github
  repo: beardeddevelopers/[repo-name]
  branch: master
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: beards
    label: Beards
    label_singular: Bearded
    description: "Fully qualified entries of Bearded Developers"
    folder: "data/bearded"
    create: true
    delete: true  # false will prevent deletions
    slug: "{{year}}-{{month}}-{{day}}-{{name}}-{{isBeardedDev}}"
    extension: json
    format: json
    identifier_field: name
    filter: {field: "isBeardedDev", value: true}
    fields:
      # name, avatar, image, isBeardedDev
      - {name: "name", label: "Name", widget: "string"}
      - {name: "avatar", label: "Avatar", widget: "image"}
      - {name: "image", label: "Image", widget: "image"}
      - {name: "isBeardedDev", label: "Is Bearded Dev?", widget: "boolean", default: true}
